version: 2

updates:
  - package-ecosystem: cargo
    directory: /rust
    target-branch: master
    schedule:
      interval: cron
      cronjob: "0 7,19 * * *"
      timezone: Australia/Sydney
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
