ARG RUST_IMAGE=rust:1.98.1-bookworm@sha256:9a73a5088750b4c95158ab26629c854c3d6fc4b173cb7bc8079ad252d8ed7bfa
ARG OCAML_IMAGE=ocaml/opam:debian-12-ocaml-5.2

FROM ${RUST_IMAGE} AS rust-toolchain
RUN rustup component add clippy rustfmt

FROM ${OCAML_IMAGE}

USER root
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        libprotobuf-dev \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY --from=rust-toolchain /usr/local/cargo /usr/local/cargo
COPY --from=rust-toolchain /usr/local/rustup /usr/local/rustup

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/workspace/_build/cargo-home \
    CARGO_TARGET_DIR=/workspace/_build/rust \
    PATH=/usr/local/cargo/bin:${PATH}

USER opam
WORKDIR /workspace
COPY --chown=opam:opam temporal-sdk.opam dune-project ./
RUN opam repository set-url default https://opam.ocaml.org \
    && opam update \
    && opam install --deps-only --with-test --no-depexts -y .

CMD ["opam", "exec", "--", "dune", "build"]
