#!/bin/sh
set -eu

# Keep a reviewable inventory of live controller and baseline workflow
# membership. This is a source/document check, never evidence of a live result.
# Only POSIX tools are used so the existing Linux and native gates can run it.
root=${1:-$(CDPATH="" cd -- "$(dirname "$0")/.." && pwd)}
mode=${2:---check}
case "$mode" in
  --check|--write) ;;
  *) echo "usage: $0 [repository-root] [--check|--write]" >&2; exit 2 ;;
esac
scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT HUP INT TERM

# Restrict extraction to the server job: source-only contract targets from
# other jobs must not be presented as additional live controllers.
workflow="$root/.github/workflows/build.yml"
if grep -F 'uses: ./.github/workflows/build-pr.yml' "$workflow" >/dev/null; then
  workflow="$root/.github/workflows/build-pr.yml"
fi
awk '
  /^  temporal-integration:/ { active = 1; next }
  active && /^  [[:alnum:]_-]+:/ { exit }
  active && match($0, /make test-temporal-[[:alnum:]-]+/) {
    print substr($0, RSTART + 5, RLENGTH - 5)
  }
' "$workflow" > "$scratch/entrypoints"

# The CI diagnostics wrapper introduced alongside this audit retains explicit
# public controller calls in one Makefile recipe. Expand that wrapper while
# excluding its Docker-free contract; accept the original direct-call workflow
# too so these independent documentation/diagnostics changes compose safely.
while IFS= read -r target; do
  if [ "$target" = test-temporal-live-ci ]; then
    awk '
      /^test-temporal-live-ci:/ { active = 1; next }
      active && /^[[:alnum:]_.-]+:/ { exit }
      active && match($0, /\$\(MAKE\) test-temporal-[[:alnum:]-]+/) {
        name = substr($0, RSTART + 8, RLENGTH - 8)
        if (name !~ /-contract$/) print name
      }
    ' "$root/Makefile"
  else
    printf '%s\n' "$target"
  fi
done < "$scratch/entrypoints" | LC_ALL=C sort -u > "$scratch/controllers"

# The baseline driver passes shared definitions with this labelled argument.
# Deduplicate references: successor waits and repeated starts are not new
# workflow capabilities. A change to this fixture convention needs a matching
# extractor update; no line numbers, start counts, or scheduling order are fixed.
sed -n 's/.*~workflow:Definitions\.\([[:alnum:]_]*\).*/\1/p' \
  "$root/test/integration/temporal/driver/smoke_driver.ml" \
  | LC_ALL=C sort -u > "$scratch/references"

if [ ! -s "$scratch/controllers" ] || [ ! -s "$scratch/references" ]; then
  echo "live inventory extraction was empty; check the fixture conventions" >&2
  exit 1
fi

# Bind the referenced OCaml definitions to their durable workflow names.
# Fail closed when a referenced definition no longer has a literal name in
# the fixture instead of silently dropping it from the generated inventory.
awk '
  FNR == NR {
    if ($0 ~ /^let [[:alnum:]_]+/) symbol = $2
    if ($0 ~ /Temporal\.Workflow\.(define|remote) ~name:"/) {
      split($0, quoted, "\"")
      names[symbol] = quoted[2]
    }
    next
  }
  !($0 in names) {
    print "cannot resolve baseline workflow definition: " $0 > "/dev/stderr"
    failed = 1
    next
  }
  { print "| `" $0 "` | `" names[$0] "` |" }
  END { if (failed) exit 1 }
' "$root/test/integration/temporal/common/smoke_definitions.ml" \
  "$scratch/references" > "$scratch/workflows"

{
  cat <<'HEADER'
# Live acceptance source inventory

Generated by `make update-live-acceptance-inventory`. Do not edit by hand.
`make check-live-acceptance-inventory` detects membership drift in the checked
source. This file records definitions and targets, not executed assertions or
successful CI evidence; see [live acceptance coverage](live-acceptance-coverage.md).

## Build live targets

Extracted from the `temporal-integration` job in
[Build](../../.github/workflows/build.yml), resolving its CI wrapper in the
[Makefile](../../Makefile) when present and sorted independently of run order.

HEADER
  # The backticks below are literal Markdown, not shell substitutions.
  # shellcheck disable=SC2016
  sed 's/^/- `make /; s/$/`/' "$scratch/controllers"
  cat <<'HEADER'

## Baseline workflow definitions

Shared [definitions](../../test/integration/temporal/common/smoke_definitions.ml)
referenced by the baseline [driver](../../test/integration/temporal/driver/smoke_driver.ml).
Repeated client starts and successor waits use the same definition; child-only
and specialized-controller workflows are described in the evidence reference.

| Fixture definition | Workflow type |
| --- | --- |
HEADER
  cat "$scratch/workflows"
} > "$scratch/inventory.md"

inventory="$root/docs/reference/live-acceptance-inventory.md"
if [ "$mode" = --write ]; then
  cp "$scratch/inventory.md" "$inventory"
else
  # Git may check Markdown out as CRLF on Windows. Compare text with only that
  # line-ending representation normalized; preserve internal whitespace and
  # every inventory member. Generation stays LF and checking never rewrites
  # the checkout. The executable script itself is pinned to LF by attributes.
  awk '{ sub(/\r$/, ""); print }' "$inventory" > "$scratch/checked-in-inventory.md"
  if ! diff -u "$scratch/checked-in-inventory.md" "$scratch/inventory.md"; then
    echo "live inventory drift: run make update-live-acceptance-inventory and review the evidence matrix" >&2
    exit 1
  fi
fi
