name: Build master

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-master-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-pr.yml
    with:
      tier: master
